FROM nginx:stable-alpine AS runner

# Remove builtin configs from parent container 
RUN rm /etc/nginx/conf.d/*

WORKDIR /app


RUN apk add --no-cache --repository=http://dl-cdn.alpinelinux.org/alpine/v3.11/main/ nodejs=12.22.6-r0 yarn


ENV FORCE_COLOR 1
ENV DATA_PATH /app/data
ENV NGINX_PATH /etc/nginx
ENV NGINX_CONFIG_PATH ${NGINX_PATH}/conf.d


CMD [ "yarn", "dev" ]