FROM node:alpine AS deps
WORKDIR /app

COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile

FROM jonasal/nginx-certbot AS runner
WORKDIR /app

RUN apt-get update
RUN apt-get install -y --no-install-recommends curl gnupg

RUN curl -sL https://deb.nodesource.com/setup_12.x | bash -
RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
RUN echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    nodejs \
    yarn

COPY . .

COPY --from=deps /app/node_modules ./node_modules

CMD [ "yarn", "dev", "& /scripts/start_nginx_certbot.sh" ]